export const USER_SIGNUP_REQUEST= "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS= "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL= "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET= "USER_SIGNUP RESET";

export const USER_SIGNIN_REQUEST= "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS= "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL= "USER_SIGIN_FAIL";
export const USER_SIGNIN_RESET= "USER_SIGNIN RESET";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET";

// export const SHOW_PROFILE_REQUEST = "SHOW_PROFILE_REQUEST";
// export const SHOW_PROFILE_SUCCESS = "SHOW_PROFILE_SUCCESS";
// export const SHOW_PROFILE_FAIL = "SHOW_PROFILE_FAIL";
// export const SHOW_PROFILE_RESET = "SHOW_PROFILE_RESET";

export const CREATE_PROFILE_PICTURE_REQUEST = "CREATE_PROFILE_PICTURE_REQUEST";
export const CREATE_PROFILE_PICTURE_SUCCESS = "CREATE_PROFILE_PICTURE_SUCCESS";
export const CREATE_PROFILE_PICTURE_FAIL = "CREATE_PROFILE_PICTURE_FAIL";
export const CREATE_PROFILE_PICTURE_RESET = "CREATE_PROFILE_PICTURE_RESET";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const DELETE_PROFILE_PICTURE_REQUEST = "DELETE_USER_PROFILE_REQUEST";
export const DELETE_PROFILE_PICTURE_SUCCESS = "DELETE_PROFILE_PICTURE_SUCCESS";
export const DELETE_PROFILE_PICTURE_FAIL = "DELETE_PROFILE_PICTURE_FAIL";
export const DELETE_PROFILE_PICTURE_RESET = "DELETE_PROFILE_PICTURE_RESET";



// export const CONFIRM_REQUEST= "CONFIRM_REQUEST";
// export const CONFIRM_SUCCESS= "CONFIRM_SUCCESS";
// export const CONFIRM_FAIL= "CONFIRM_FAIL";
// export const CONFIRM_RESET= "CONFIRM_RESET";

