export const USER_SIGNUP_REQUEST= "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS= "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL= "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET= "USER_SIGNUP RESET";

export const USER_SIGNIN_REQUEST= "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS= "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL= "USER_SIGIN_FAIL";
export const USER_SIGNIN_RESET= "USER_SIGNIN RESET";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";
export const UPDATE_USER_PROFILE_RESET = "UPDATE_USER_PROFILE_RESET";

export const DELETE_USER_PROFILE_REQUEST = "DELETE_USER_PROFILE_REQUEST";
export const DELETE_USER_PROFILE_SUCCESS = "DELETE_USER_PROFILE_SUCCESS";
export const DELETE_USER_PROFILE_FAIL = "DELETE_USER_PROFILE_FAIL";
export const DELETE_USER_PROFILE_RESET = "DELETE_USER_PROFILE_RESET";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET";

